services:
  backend:
    build: ./backend
    container_name: academic-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - academic-network

  frontend:
    build: ./frontend
    container_name: academic-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app           # Maps your code
      - frontend_node_modules:/app/node_modules
      - /app/.next                # <--- ADD THIS TOO (Speeds up build)
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=500
    command: sh -c "npm install --include=optional && npm run dev"
    depends_on:
      - backend
    networks:
      - academic-network

networks:
  academic-network:
    driver: bridge

volumes:
  frontend_node_modules:
